### ISSUE TITLE
Feature: Add SSH server port in "Connection Settings"

### ISSUE THREAD

**Issue by mueckinger** [SJBERTRAND/portforwarding-extension#2]
I am very paranoid and never use default ssh port on public facing ssh servers. This is usually defined with the ssh -p flag. I would appreciate being able to set this in the "Connection Settings".
For the time being you can define the port in your .ssh/config and use the "Host" configured there in the "Enter remote address/ip" field of the extensions "Connection Settings" as a workaround.

**Comment by SJBERTRAND** [comment]
Done. The new extension version should be available shortly on the gnome-extension website
